//
//  Answer.swift
//  who wants to be a millionaire
//
//  Created by John Lin on 2020-03-16.
//  Copyright © 2020 John Lin. All rights reserved.
//

import Foundation

enum Answer: String, CaseIterable {
    case ONE_1 = "Beep! Beep!"
    case ONE_2 = "Ping! Ping!"
    case ONE_3 = "Aooga! Aooga!"
    case ONE_4 = "Vroom! Vroom!"
    case TWO_1 = "Around the throat"
    case TWO_2 = "On the knees"
    case TWO_3 = "Over the eyes"
    case TWO_4 = "On the hips"
    case THREE_1 = "Polka"
    case THREE_2 = "Swing"
    case THREE_3 = "Lambada"
    case THREE_4 = "Hora"
    case FOUR_1 = "Pig Latin"
    case FOUR_2 = "Dog Latin"
    case FOUR_3 = "Duck Latin"
    case FOUR_4 = "Bull Latin"
    case FIVE_1 = "Leg"
    case FIVE_2 = "Breast"
    case FIVE_3 = "Wing"
    case FIVE_4 = "Gizzard"
    case SIX_1 = "Quarterback"
    case SIX_2 = "Tight End"
    case SIX_3 = "Center"
    case SIX_4 = "Wide Receiver"
    case SEVEN_1 = "Cupid"
    case SEVEN_2 = "Zeus"
    case SEVEN_3 = "Mercury"
    case SEVEN_4 = "Poseidon"
    case EIGHT_1 = "Close Encounters of the Third Kind"
    case EIGHT_2 = "Jurassic Park"
    case EIGHT_3 = "Raider of the Lost Ark"
    case EIGHT_4 = "E.T. the Extra-Terrestrial"
    case NINE_1 = "Tombstone"
    case NINE_2 = "Laramie"
    case NINE_3 = "El Paso"
    case NINE_4 = "Dodge City"
    case TEN_1 = "August"
    case TEN_2 = "November"
    case TEN_3 = "February"
    case TEN_4 = "September"
    case ELEVEN_1 = "Phoenix"
    case ELEVEN_2 = "Minotaur"
    case ELEVEN_3 = "Golem"
    case ELEVEN_4 = "Dragon"
    case TWELVE_1 = "Jonas Salk"
    case TWELVE_2 = "Albert Sabin"
    case TWELVE_3 = "Niels Bohr"
    case TWELVE_4 = "Louis Pasteur"
    case THIRTEEN_1 = "Hinduism"
    case THIRTEEN_2 = "Islam"
    case THIRTEEN_3 = "Judaism"
    case THIRTEEN_4 = "Christianity"
    case FOURTEEN_1 = "I.M. Pei"
    case FOURTEEN_2 = "Le Corbusier"
    case FOURTEEN_3 = "Frank Gehry"
    case FOURTEEN_4 = "Phillip Johnson"
    case FIFTEEN_1 = "Richard Nixon"
    case FIFTEEN_2 = "Lyndon Johnson"
    case FIFTEEN_3 = "Gerald Ford"
    case FIFTEEN_4 = "Jimmy Carter"
}
